name: Node.js CI

on: [push]

env:
###################################################################
# This token is provided during the creation of your user account
# on a Harbormaster instance.  If you do not have your token,
# contact your Harbormaster administrator.
###################################################################
    HARBORMASTER_API_TOKEN: "sny6iLHAH4SMJU1F"


###################################################################
# This is the location and name of the file to provide to 
# Harbormaster containing your directives to generate the project
#
# To learn more, visithttps://harbormaster.ai/2025/harbormaster-project-commands/
###################################################################
    PROJECT_YAML_FILE: "samples/yamls/project-as-code/django-project-as-code.yml"
                        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: print env
        run: printenv
      - name: Install Harbormaster
        run: npm install -g harbormaster-ai
      - name: Initialize Harbormaster with provided token   
        run: harbormaster init $HARBORMASTER_API_TOKEN
      - name: Generating project on file from the working dir $GITHUB_WORKSPACE...
        run: harbormaster project_generate $GITHUB_WORKSPACE/$PROJECT_YAML_FILE -q true
      
