name: Harbormaster Project Accelerator GitHub Action

on: [push]

env:
###################################################################
# This token is provided during the creation of your user account
# on a Harbormaster instance.  
#
# For security purposes, you should store is as a development environment secret
# within GitHub and refer to it here.
#
# If you do not have your token,
# contact your Harbormaster administrator.
###################################################################
    HARBORMASTER_API_TOKEN: "sny6iLHAH4SMJU1F"

###################################################################
# the location of the Harbormaster Instanmce to connect to
# leave it blank to use the default public instance
###################################################################
    HARBORMASTER_INSTANCE_URL: "http://35.184.162.42:8080/service"
    
###################################################################
# This is the location and name of the file to provide to 
# Harbormaster containing your directives to generate the project
# The file used here is relative to GitHub env var $GITHUB_WORKSPACE
# To learn more, visit https://harbormaster.ai/2025/harbormaster-project-commands/
###################################################################
    PROJECT_YAML_FILE: "samples/yamls/project.as.code/django-project-as-code.yml"
                        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
        
###################################################################
# Harbormaster CLI is a NodeJS pacage.  It first must be installed
###################################################################
      - name: Install Harbormaster
        run: npm install -g harbormaster-ai
        
###################################################################
# Once installed, it can be run using it's registered name of harbormaster
# The token is provided here to validate your credentials
#
# If a connection to the default public instance is to be used, 
# the url parameter can be left blank.  If accessing a different
# instance, its URL must be provided.
###################################################################
      - name: Initialize Harbormaster 
        run: harbormaster init $HARBORMASTER_API_TOKEN $HARBORMASTER_INSTANCE_URL
            
      - name: Generate project
        run: harbormaster project_generate $GITHUB_WORKSPACE/$PROJECT_YAML_FILE      
